Geocoder.configure(

  # geocoding service (see below for supported options):
  :lookup => :google,
  :language => 'ko',

  # IP address geocoding service (see below for supported options):
  :ip_lookup => :maxmind,

  # to use an API key:
  # Generated by kty1965@gmail.com
  :api_key => "AIzaSyCDXiYTkFqUBVfv6k4tAf6lo8MOC6CS-kc",

  # geocoding service request timeout, in seconds (default 3):
  :timeout => 5,

  # set default units to kilometers:
  :units => :km,

  # caching (see below for details):
  # :cache => Redis.new,
  # :cache_prefix => geocode

)